### ISSUE TITLE
Organização de Estrutura

### ISSUE THREAD

**Issue by DaniloOPinheiro** [Alan-Reis/Algoritmo#1]
1. Ideal que separe por diretorio, para que as classes não fiquei soltas.
2. Usar melhores praticas possiveis, como por exemplo; usar tratamento de orietação a objeto.
Dica : https://www.devmedia.com.br/os-4-pilares-da-programacao-orientada-a-objetos/9264

**Comment by Alan-Reis** [comment]
Concluido
